// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Contracts
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class Order : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""Order"",""namespace"":""Contracts"",""fields"":[{""name"":""CreatedAt"",""type"":""string""},{""name"":""Dishes"",""type"":{""type"":""array"",""items"":{""type"":""record"",""name"":""Dish"",""namespace"":""Contracts"",""fields"":[{""name"":""Cost"",""type"":{""type"":""bytes"",""logicalType"":""decimal"",""precision"":29,""scale"":2}},{""name"":""Id"",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""Title"",""type"":""string""}]}}},{""name"":""Id"",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""TotalCost"",""type"":{""type"":""bytes"",""logicalType"":""decimal"",""precision"":29,""scale"":2}}]}");
		private string _CreatedAt;
		private IList<Contracts.Dish> _Dishes;
		private System.Guid _Id;
		private Avro.AvroDecimal _TotalCost;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return Order._SCHEMA;
			}
		}
		public string CreatedAt
		{
			get
			{
				return this._CreatedAt;
			}
			set
			{
				this._CreatedAt = value;
			}
		}
		public IList<Contracts.Dish> Dishes
		{
			get
			{
				return this._Dishes;
			}
			set
			{
				this._Dishes = value;
			}
		}
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				this._Id = value;
			}
		}
		public Avro.AvroDecimal TotalCost
		{
			get
			{
				return this._TotalCost;
			}
			set
			{
				this._TotalCost = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.CreatedAt;
			case 1: return this.Dishes;
			case 2: return this.Id;
			case 3: return this.TotalCost;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.CreatedAt = (System.String)fieldValue; break;
			case 1: this.Dishes = (IList<Contracts.Dish>)fieldValue; break;
			case 2: this.Id = (System.Guid)fieldValue; break;
			case 3: this.TotalCost = (Avro.AvroDecimal)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
